version: '3'

services:
    php_5_6:
        image:  php:5.6-fpm
        container_name: php_5_6
        tty:  true
        working_dir:  /var/www
        volumes:
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./project/:/var/www
        networks:
            - local-bridge
        
    nginx:
        image:  nginx:alphine
        container_name: nginx
        tty: true
        volumes:
            - ./project/:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - local-bridge
networks:
    local-bridge:
        driver: bridge




